version: 1.0.0.{build}
image: Visual Studio 2019

configuration: Release
platform: AnyCPU

before_build:
- cmd: >-
    nuget restore "AION Chat.csproj" -PackagesDirectory ../packages
    
    msbuild.exe "AION Chat.csproj"

build:
  verbosity: minimal